// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/taylormonacelli/illprogram/core

package core

#Template: {
	template: string @go(Template)
	path:     string @go(Path)
}

#Config: {
	templates: [...#Template] @go(Templates,[]Template)
}

#Data: [string]: #Config
